name: Scrape RepliQ Videos

on:
  push:
    branches:
      - main
    paths:
      - 'RepliQ_results.csv'
      
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraping script
        run: python 1_create_layered_videos_json.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated videos.json and CSV with final links"
          # --- FIX: Removed the single quotes around the second filename ---
          file_pattern: "videos.json RepliQ_results.csv"

